//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompanyServiceHttpPublic.CompanyService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CompanyService.ICompanyPublicService")]
    public interface ICompanyPublicService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompanyPublicService/PublicInformation", ReplyAction="http://tempuri.org/ICompanyPublicService/PublicInformationResponse")]
        string PublicInformation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompanyPublicService/PublicInformation", ReplyAction="http://tempuri.org/ICompanyPublicService/PublicInformationResponse")]
        System.Threading.Tasks.Task<string> PublicInformationAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICompanyPublicServiceChannel : CompanyServiceHttpPublic.CompanyService.ICompanyPublicService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CompanyPublicServiceClient : System.ServiceModel.ClientBase<CompanyServiceHttpPublic.CompanyService.ICompanyPublicService>, CompanyServiceHttpPublic.CompanyService.ICompanyPublicService {
        
        public CompanyPublicServiceClient() {
        }
        
        public CompanyPublicServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CompanyPublicServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompanyPublicServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompanyPublicServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string PublicInformation() {
            return base.Channel.PublicInformation();
        }
        
        public System.Threading.Tasks.Task<string> PublicInformationAsync() {
            return base.Channel.PublicInformationAsync();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CompanyService.ICompanyPrivateService")]
    public interface ICompanyPrivateService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompanyPrivateService/PrivateInformation", ReplyAction="http://tempuri.org/ICompanyPrivateService/PrivateInformationResponse")]
        string PrivateInformation();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICompanyPrivateService/PrivateInformation", ReplyAction="http://tempuri.org/ICompanyPrivateService/PrivateInformationResponse")]
        System.Threading.Tasks.Task<string> PrivateInformationAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICompanyPrivateServiceChannel : CompanyServiceHttpPublic.CompanyService.ICompanyPrivateService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CompanyPrivateServiceClient : System.ServiceModel.ClientBase<CompanyServiceHttpPublic.CompanyService.ICompanyPrivateService>, CompanyServiceHttpPublic.CompanyService.ICompanyPrivateService {
        
        public CompanyPrivateServiceClient() {
        }
        
        public CompanyPrivateServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CompanyPrivateServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompanyPrivateServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompanyPrivateServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string PrivateInformation() {
            return base.Channel.PrivateInformation();
        }
        
        public System.Threading.Tasks.Task<string> PrivateInformationAsync() {
            return base.Channel.PrivateInformationAsync();
        }
    }
}
