using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using TeacherObject;

/*
 even after putting the teacherObject separately as DLL, the issue of reference.cs generating as an
 errorneous file is not fixed.
 we will need to mannually replace all the occurences of 'namespace.ServiceReference' in the autogenerated reference.cs
 file with ServiceReference1
     */

namespace TeacherServiceClient
{
    public partial class WebForm1 : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {
            if (!IsPostBack)
            {
                ServiceReference1.TeacherServiceClient client =
                    new ServiceReference1.TeacherServiceClient("BasicHttpBinding_ITeacherService");

                ddlDepartment.DataSource = client.ShowAllDepartments();
                ddlDepartment.DataTextField = "Text";
                ddlDepartment.DataValueField = "Value";
                ddlDepartment.DataBind();
                //ddlDepartment.Items.Insert(0, new ListItem("Select Department", "-1"));

                trannualsal.Visible = false;
                trhpay.Visible = false;
                trhw.Visible = false;

            }
        }

        protected void btnFetchTeacher_Click(object sender, EventArgs e)
        {
            LblMessage.Text = ddlDepartment.SelectedItem.Text + " " + ddlDepartment.SelectedItem.Value;
            ServiceReference1.TeacherServiceClient client =
                new ServiceReference1.TeacherServiceClient(); //since only one end point is there,no need specify binding specifically
            TeacherItem teacher = client.ShowTeacherByID(Convert.ToInt32(txtID.Text));
            if (teacher != null)
            {
                txtName.Text = teacher.TeacherName;
                txtQual.Text = teacher.TeacherQualification;
                //txtSalary.Text = teacher.Salary.ToString();
                if (teacher.GetType() == typeof(FullTimeTeacher))
                {
                    txtAnnualSal.Text = (((FullTimeTeacher)teacher).AnnualPackage).ToString();
                    trannualsal.Visible = true;
                    trhw.Visible = false;
                    trhpay.Visible = false;
                }
                else
                {
                    trannualsal.Visible = false;
                    trhw.Visible = true;
                    trhpay.Visible = true;
                    txtHourlyPay.Text= (((PartTimeTeacher)teacher).HourlyPay).ToString();
                    txtHoursWorked.Text= (((PartTimeTeacher)teacher).HoursWorked).ToString();
                }
                ddlGender.SelectedValue = ((int)teacher.Gender).ToString();
                ddlEmpType.SelectedValue = (Convert.ToInt32(teacher.Type)).ToString();
                ddlDepartment.SelectedItem.Text = teacher.Department.Name;
                ddlDepartment.SelectedItem.Value = teacher.Department.DeptID.ToString();
                LblMessage.Text = "Teacher Found..!!";
            }
            else
            {
                LblMessage.Text = "Teacher Not Found..!!";
                txtName.Text = string.Empty;
                txtQual.Text = string.Empty;
                txtHoursWorked.Text = string.Empty;
                txtHourlyPay.Text = string.Empty;
                txtAnnualSal.Text = string.Empty;
                trannualsal.Visible = false;
                trhw.Visible = false;
                trhw.Visible = false;
                ddlGender.SelectedValue = "-1";
                ddlEmpType.SelectedValue = "-1";
                ddlDepartment.SelectedItem.Text = "Select Department";
                ddlDepartment.SelectedItem.Text = "-1";
            }
        }

        protected void btnInsertTeacher_Click(object sender, EventArgs e)
        {
            ServiceReference1.TeacherServiceClient client =
                new ServiceReference1.TeacherServiceClient();
            TeacherItem teacher =new TeacherItem();
            if (EmployeeType.FullTimeTeacher == (EmployeeType)Convert.ToInt32(ddlEmpType.SelectedValue))
            {
                FullTimeTeacher fteacher = new FullTimeTeacher();
                fteacher.AnnualPackage = Convert.ToInt32(txtAnnualSal.Text);
                teacher = fteacher;
            }
            else
            {
                PartTimeTeacher pteacher = new PartTimeTeacher();
                pteacher.HourlyPay = Convert.ToInt32(txtHourlyPay.Text);
                pteacher.HoursWorked = Convert.ToInt32(txtHoursWorked.Text);
                teacher = pteacher;
            }
            teacher.TeacherName = txtName.Text;
            teacher.TeacherQualification = txtQual.Text;
            //teacher.Salary = Convert.ToInt32(txtSalary.Text);
            teacher.Department = new DepartmentItem()
            {
                Name = ddlDepartment.SelectedItem.Text,
                DeptID = Convert.ToInt32(ddlDepartment.SelectedItem.Value)
            };
            //teacher.Department.DeptID = Convert.ToInt32(ddlDepartment.SelectedItem.Value);
            teacher.Gender = (Gender) Convert.ToInt32( ddlGender.SelectedValue);
            teacher.Type = (EmployeeType)Convert.ToInt32( ddlEmpType.SelectedValue);
            

            int result = client.InsertNewEmployee(teacher);
            if (result > 0)
            {
                LblMessage.Text = "Teacher Inserted with Employee ID: " + result.ToString();
            }
        }

        protected void ddlEmpType_SelectedIndexChanged(object sender, EventArgs e)
        {
            if (ddlEmpType.SelectedValue == "1")
            {
                trannualsal.Visible = true;
                trhw.Visible = false;
                trhpay.Visible = false;
            }
            else if (ddlEmpType.SelectedValue == "2")
            {
                trannualsal.Visible = false;
                trhw.Visible = true;
                trhpay.Visible = true;
            }
            else
            {
                trannualsal.Visible = false;
                trhw.Visible = false;
                trhpay.Visible = false;
            }
        }
    }
}