//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NamedServiceContractClient.HelloService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HelloService.INamedServiceContracts")]
    public interface INamedServiceContracts {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INamedServiceContracts/SayHello", ReplyAction="http://tempuri.org/INamedServiceContracts/SayHelloResponse")]
        string SayHello(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INamedServiceContracts/SayHello", ReplyAction="http://tempuri.org/INamedServiceContracts/SayHelloResponse")]
        System.Threading.Tasks.Task<string> SayHelloAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INamedServiceContractsChannel : NamedServiceContractClient.HelloService.INamedServiceContracts, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NamedServiceContractsClient : System.ServiceModel.ClientBase<NamedServiceContractClient.HelloService.INamedServiceContracts>, NamedServiceContractClient.HelloService.INamedServiceContracts {
        
        public NamedServiceContractsClient() {
        }
        
        public NamedServiceContractsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NamedServiceContractsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NamedServiceContractsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NamedServiceContractsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SayHello(string name) {
            return base.Channel.SayHello(name);
        }
        
        public System.Threading.Tasks.Task<string> SayHelloAsync(string name) {
            return base.Channel.SayHelloAsync(name);
        }
    }
}
