using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Services;

namespace WebServicesDemo
{
    /*the below three lines are autogenerated*/
    /// <summary>
    /// Summary description for CalculatorWebService
    /// </summary>
    [WebService(Namespace = "http://tempuri.org/")]//this attribute says that class CalculatorWebService is web service.
    /*Namespace are used to uniquely identify from other
    webservices currently on the web. Ideally give organisation domain here.
    like, http://pragimtech.com/webservices/
      */

    [WebServiceBinding(ConformsTo = WsiProfiles.BasicProfile1_1)]
    [System.ComponentModel.ToolboxItem(false)]
    
    /*Impotant point to note the below comment.*/
    // To allow this Web Service to be called from script, using ASP.NET AJAX, uncomment the following line. 
    // [System.Web.Script.Services.ScriptService]
    public class CalculatorWebService : System.Web.Services.WebService
    /*Note the inheriting from System.Web.Services.WebService is not necessary. But if this webservice intends to
     use the Http Session State or application state objects then it this inheritance allows the webservice
     to have a direct access to those objects.
     */
    {

        [WebMethod]
        /*if you want to expose this method as part of this webservice , then we need to decorate the method
         with  [WebMethod] attribute. */
        public int Add(int firstNumber, int secondNumber) //the method should be public as well.
        {
            return firstNumber+secondNumber;
        }
    }
}
