//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFWithAjaxClient.WCFWithAjaxDemoService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://schemas.datacontract.org/2004/07/WCFWithAjax")]
    [System.SerializableAttribute()]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float SalaryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Salary {
            get {
                return this.SalaryField;
            }
            set {
                if ((this.SalaryField.Equals(value) != true)) {
                    this.SalaryField = value;
                    this.RaisePropertyChanged("Salary");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFWithAjaxDemoService.IWCFWithAjaxService")]
    public interface IWCFWithAjaxService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFWithAjaxService/SaveEmployee", ReplyAction="http://tempuri.org/IWCFWithAjaxService/SaveEmployeeResponse")]
        int SaveEmployee(WCFWithAjaxClient.WCFWithAjaxDemoService.Employee employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFWithAjaxService/SaveEmployee", ReplyAction="http://tempuri.org/IWCFWithAjaxService/SaveEmployeeResponse")]
        System.Threading.Tasks.Task<int> SaveEmployeeAsync(WCFWithAjaxClient.WCFWithAjaxDemoService.Employee employee);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFWithAjaxService/GetEmployeeByID", ReplyAction="http://tempuri.org/IWCFWithAjaxService/GetEmployeeByIDResponse")]
        WCFWithAjaxClient.WCFWithAjaxDemoService.Employee GetEmployeeByID(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFWithAjaxService/GetEmployeeByID", ReplyAction="http://tempuri.org/IWCFWithAjaxService/GetEmployeeByIDResponse")]
        System.Threading.Tasks.Task<WCFWithAjaxClient.WCFWithAjaxDemoService.Employee> GetEmployeeByIDAsync(int ID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFWithAjaxServiceChannel : WCFWithAjaxClient.WCFWithAjaxDemoService.IWCFWithAjaxService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFWithAjaxServiceClient : System.ServiceModel.ClientBase<WCFWithAjaxClient.WCFWithAjaxDemoService.IWCFWithAjaxService>, WCFWithAjaxClient.WCFWithAjaxDemoService.IWCFWithAjaxService {
        
        public WCFWithAjaxServiceClient() {
        }
        
        public WCFWithAjaxServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFWithAjaxServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFWithAjaxServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFWithAjaxServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int SaveEmployee(WCFWithAjaxClient.WCFWithAjaxDemoService.Employee employee) {
            return base.Channel.SaveEmployee(employee);
        }
        
        public System.Threading.Tasks.Task<int> SaveEmployeeAsync(WCFWithAjaxClient.WCFWithAjaxDemoService.Employee employee) {
            return base.Channel.SaveEmployeeAsync(employee);
        }
        
        public WCFWithAjaxClient.WCFWithAjaxDemoService.Employee GetEmployeeByID(int ID) {
            return base.Channel.GetEmployeeByID(ID);
        }
        
        public System.Threading.Tasks.Task<WCFWithAjaxClient.WCFWithAjaxDemoService.Employee> GetEmployeeByIDAsync(int ID) {
            return base.Channel.GetEmployeeByIDAsync(ID);
        }
    }
}
